name: Auto Approve PR

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [labeled]

jobs:
  auto-approve:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'APPROVE'
            })
